---
- name: Install and Start Service
  hosts: localhost

  tasks:
    - name: Installing Nginx
      yum:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
