---
- name: File Module
  hosts: localhost
  tasks:
    - name: Create a file
      file: 
        path: /home/centos/file1.txt
        state: touch
        # state: absent (to delete the file)
        owner: centos
        group: centos
        mode: 0777

    - name: Create a directory
      file:
        path: /home/centos/dir1
        state: directory
        # state: absent (to delete the directory)
        owner: centos
        group: centos