---
- name: Set Password
  hosts: localhost

  tasks:
    - name: Set Password
      user:
        name: "centos"
        update_password: always
        password: {{ 'centos_password' | password_hash('sha512') }}